#include <cassert>
#include <iostream>
#include "ComplexNumber.hpp"

using namespace std;

//int main()
//{
//    ComplexNumber jack = ComplexNumber(3,5);
//    ComplexNumber Jill = ComplexNumber(7, 10);
//
//    cout << "Starting tests..." << endl;
//    cout << jack.get_form() << endl << "is Jack" << endl;
//    cout << Jill.get_form() << endl << "is Jill" << endl;
//    cout << jack.addition(Jill) << " Your test is successful" << endl;
//    cout << jack.subtraction(Jill) << " Your test is successful" << endl;
//    cout << jack.multiplication(Jill) << " Your test is successful" << endl;
//    cout << jack.division(Jill) << " Your test is successful" << endl;
//}